# Docker compose example
# Add this service to your existing docker-compose.yml

services:
  devestreamingplatformweb:
    build: .
    container_name: deveplatform_web
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - BASIC_AUTH_USERNAME=${WEB_USERNAME:-admin}
      - BASIC_AUTH_PASSWORD=${WEB_PASSWORD:-changeme}
    networks:
      - streaming_network

networks:
  streaming_network:
    external: true
